### ISSUE TITLE
Instagram link on main page is not correct

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/main-site#1]
The Instagram link on the main page leads to an incorrect URL.
Currently it leads here:
https://www.instagram.com/museumofthejewishpeople/

**Comment by Gupo** [comment]
@nirgoldberg Danna has the correct URL and will replace it.

**Comment by nirgoldberg** [comment]
@TheGrandVizier Please assign to Libi or Danna

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/wp-bh#1
