### ISSUE TITLE
Explorer problem when ordering tickets

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/main-site#2]
When clicking "Order tickets" in explorer (windows 7),
The ticketnet window opens correctly, but the main site window turns into this:
http://prntscr.com/c0jamh

a white page with the word "object".
This does not prevent people from ordering tickets.

**Comment by nirgoldberg** [comment]
Fixed for event pages (auto generated purchase buttons)

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/wp-bh#2
